{
  super.resume();
  try {
    Debug.logVerbose("Checking to see if we can complete the activity",module);
    this.checkComplete();
  }
 catch (  CannotComplete e) {
    throw new CannotResume("Attempt to complete activity failed",e);
  }
}
